### ISSUE TITLE
DİL

### ISSUE THREAD

**Issue by GamzeSirakaya** [arabamcom/android-assignment#1]
merhaba yapacağımız uygulamayı java ile yazabilirmiyiz.

**Comment by yusufcakmak** [comment]
@GamzeSirakaya java ile geliştirme yapabilirsiniz. Uygulama da güncel geliştirmeleri Kotlin ile yapıyoruz, bu nedenle Kotlin bilgisi veya deneyimi de önemli olacak.

**Comment by GamzeSirakaya** [comment]
Merhaba yusuf bey ,istenilen url istek atıyorum ama atılan isteğe bir değer dönmüyorİnterface classım bu şekilde;@GET("/listing/")Call<List<Root>> data(@Query("sort") int sort,                      @Query("sortDirection") int sortDirection,                      @Query("take") int take);  Bu şekilde tanımladım ve testde ettim farklı bir api ile Nerede bir yanlışlık var çözemedim yardımcı olurmusunuz.String data_url="http://sandbox.arabamd.com/api/v1/";   Windows 10 için Posta ile gönderildi Kimden: YusufGönderilme: 27 Ocak 2021 Çarşamba 19:58Kime: arabamcom/android-assignmentBilgi: Gamze Sırakaya; MentionKonu: Re: [arabamcom/android-assignment] DİL (#1) @GamzeSirakaya java ile geliştirme yapabilirsiniz. Uygulama da güncel geliştirmeleri Kotlin ile yapıyoruz, bu nedenle Kotlin bilgisi veya deneyimi de önemli olacak.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yusufcakmak** [comment]
Tanımladığınız parametreler ile birlikte istek attığınızda, url in şu şekilde olması lazım. 
`http://sandbox.arabamd.com/api/v1/listing?sort=0&sortDirection=0&take=20`

Size empty array dönüyorsa, parametreleri gönderemiyor olabilirsiniz. Aşağıdaki gibi atıyorsanız isteği, empty array dönecektir.

`http://sandbox.arabamd.com/api/v1/listing`

Loglayıp, istek attığınız urli parametreleri ile birlikte paylaşırsanız yardımcı olmaya çalışalım.

**Comment by perihanimamoglu** [comment]
> @get("listing")
Call<List< Root >> data(@query("sort") int sort, @query("sortDirection") int sortDirection, @query("take") int take);

Selam Gamze 👋, bu şekilde güncellersen sorununun düzeleceğini düşünüyorum.

**Comment by GamzeSirakaya** [comment]
Perihan hanım ,Root classımın içerisinde vermiş olduğunuz api’ nin değişkenleri vs. var ve liste olarak da Root classını kullanmam gerekiyor. O yüzden interface classım bu şekilde log olarak çağırdığım yerde de root classının içerisinde yer alan toString methodunu çağırıyorum. fakat yine bir cevap alamıyorum.Log.i("denemee",response.body().toString()); Call<List<Root>> data(@Query("sort") int sort,                      @Query("sortDirection") int sortDirection,                      @Query("take") int take);   Windows 10 için Posta ile gönderildi Kimden: Perihan İmamoğluGönderilme: 28 Ocak 2021 Perşembe 16:03Kime: arabamcom/android-assignmentBilgi: Gamze Sırakaya; MentionKonu: Re: [arabamcom/android-assignment] DİL (#1) @get("listing")Call<List> data(@query("sort") int sort, @query("sortDirection") int sortDirection, @query("take") int take);Selam Gamze 👋, bu şekilde güncellersen sorununun düzeleceğini düşünüyorum.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by perihanimamoglu** [comment]
Öncelikle bana Perihan diyebilirsin :) Evet o konuda haklısın, gözümden kaçmış, seni yanlış yönlendirmişim.

BASE_URL = "http://sandbox.arabamd.com/api/v1/" bu iken
@get("/listing/") bu şekilde tanımlarsan
"http://sandbox.arabamd.com/api/v1//listing/" şeklinde bir url'e gitmeye çalıştığı için hata alırsın. Yapman gereken @get("/listing/") -> @get("listing") bu şekilde düzenlemek olacak.

> @get("listing")
Call<List< Root >> data(@query("sort") int sort, @query("sortDirection") int sortDirection, @query("take") int take);

**Comment by GamzeSirakaya** [comment]
Teşekkürler 😊 github’da sizi public olarak eklediğim projede istek atma kodlarım yer almakta dediklerinizi uyguladım fakat bir sonuç dönmedi .Github’a bakabilirmisiniz rica etsem . Windows 10 için Posta ile gönderildi Kimden: Perihan İmamoğluGönderilme: 28 Ocak 2021 Perşembe 16:49Kime: arabamcom/android-assignmentBilgi: Gamze Sırakaya; MentionKonu: Re: [arabamcom/android-assignment] DİL (#1) Öncelikle bana Perihan diyebilirsin :) Evet o konuda haklısın, gözümden kaçmış, seni yanlış yönlendirmişim.BASE_URL = "http://sandbox.arabamd.com/api/v1/" bu iken@get("/listing/") bu şekilde tanımlarsan"http://sandbox.arabamd.com/api/v1//listing/" şeklinde bir url'e gitmeye çalıştığı için hata alırsın. Yapman gereken @get("/listing/") -> @get("listing") bu şekilde düzenlemek olacak.@get("listing")Call<List< Root >> data(@query("sort") int sort, @query("sortDirection") int sortDirection, @query("take") int take);—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by GamzeSirakaya** [comment]
Şuan sorunum çözüldü Çok teşekkür ederim 😊 Windows 10 için Posta ile gönderildi Kimden: Perihan İmamoğluGönderilme: 28 Ocak 2021 Perşembe 16:49Kime: arabamcom/android-assignmentBilgi: Gamze Sırakaya; MentionKonu: Re: [arabamcom/android-assignment] DİL (#1) Öncelikle bana Perihan diyebilirsin :) Evet o konuda haklısın, gözümden kaçmış, seni yanlış yönlendirmişim.BASE_URL = "http://sandbox.arabamd.com/api/v1/" bu iken@get("/listing/") bu şekilde tanımlarsan"http://sandbox.arabamd.com/api/v1//listing/" şeklinde bir url'e gitmeye çalıştığı için hata alırsın. Yapman gereken @get("/listing/") -> @get("listing") bu şekilde düzenlemek olacak.@get("listing")Call<List< Root >> data(@query("sort") int sort, @query("sortDirection") int sortDirection, @query("take") int take);—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
