### ISSUE TITLE
Fotograf

### ISSUE THREAD

**Issue by GamzeSirakaya** [arabamcom/android-assignment#2]
merhaba Perihan hanım, Listeleme sayfası için çekmek istediğim fotoğrafı gerekli kütüphaneleri vs. tanımlamama rağmen gelmedi.
bana bu konuda yardımcı olur musunuz.

**Comment by perihanimamoglu** [comment]
Selam Gamze, image url'i replace etmen gerekiyor. Tips kısmında bundan bahsetmiştik.

**Comment by GamzeSirakaya** [comment]
Bu replace işlemini yapabilmek için android tarafında mı değişiklik yapmam gerekiyor. Windows 10 için Posta ile gönderildi Kimden: Perihan İmamoğluGönderilme: 29 Ocak 2021 Cuma 22:52Kime: arabamcom/android-assignmentBilgi: Gamze Sırakaya; AuthorKonu: Re: [arabamcom/android-assignment] Fotograf (#2) Selam Gamze, image url'i replace etmen gerekiyor. Tips kısmında bundan bahsetmiştik.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by perihanimamoglu** [comment]
String bir değişkeni nasıl replace edebilirim, bunu araştırman gerekiyor. 

-> https://arbstorage.mncdn.com/ilanfotograflari/2020/12/18/16220679/c7bf58a1-9373-4098-8664-94a9c578e02d_image_for_silan_16220679_{0}.jpg

-> https://arbstorage.mncdn.com/ilanfotograflari/2020/12/18/16220679/c7bf58a1-9373-4098-8664-94a9c578e02d_image_for_silan_16220679_800x600.jpg

**Comment by GamzeSirakaya** [comment]
Sorunum çözüldü teşekkürler. Windows 10 için Posta ile gönderildi Kimden: Perihan İmamoğluGönderilme: 30 Ocak 2021 Cumartesi 13:04Kime: arabamcom/android-assignmentBilgi: Gamze Sırakaya; AuthorKonu: Re: [arabamcom/android-assignment] Fotograf (#2) String bir değişkeni nasıl replace edebilirim, bunu araştırman gerekiyor.-> https://arbstorage.mncdn.com/ilanfotograflari/2020/12/18/16220679/c7bf58a1-9373-4098-8664-94a9c578e02d_image_for_silan_16220679_{0}.jpg-> https://arbstorage.mncdn.com/ilanfotograflari/2020/12/18/16220679/c7bf58a1-9373-4098-8664-94a9c578e02d_image_for_silan_16220679_800x600.jpg—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
