### ISSUE TITLE
List endpoint page querry hakkında

### ISSUE THREAD

**Issue by ertugrulkaragoz** [arabamcom/android-assignment#4]
Merhaba,
List endpoint'inde paging için page query'si nasıl verebilirim? Dökümantasyonda  gösterilmemiş.

**Comment by yusufcakmak** [comment]
Dökümanda aşağıdaki gibi bir tip ve endpoint örneği eklemiştik. her page için kaç item göstereceğine karar verip, ona göre pagination yapabilirsin. 
> **Tips** -> For the pagination feature, you can use the **take** and **skip** parameters shown in the API docs.
curl -X GET "http://sandbox.arabamd.com/api/v1/listing?sort=1&sortDirection=0&take=10" -H "accept: text/plain"

hint:
http://sandbox.arabamd.com/api/v1/listing?sort=0&sortDirection=0&skip=0&take=5 
http://sandbox.arabamd.com/api/v1/listing?sort=0&sortDirection=0&skip=5&take=5
